-- AlterTable
ALTER TABLE "ScenarioResults" ADD COLUMN     "partA_c4_diff_to_wti_usd_bbl" DOUBLE PRECISION,
ADD COLUMN     "partA_c4_price_cad_m3" DOUBLE PRECISION,
ADD COLUMN     "partA_c4_price_pct_wti" DOUBLE PRECISION,
ADD COLUMN     "partA_c4_purchase_price_usd_bbl" DOUBLE PRECISION,
ADD COLUMN     "partA_condensate_eq_credit_cad_m3" DOUBLE PRECISION,
ADD COLUMN     "partA_condensate_index_usd_bbl" DOUBLE PRECISION,
ADD COLUMN     "partA_condensate_par_price_cad_m3" DOUBLE PRECISION,
ADD COLUMN     "partA_condensate_price_after_eq_cad_m3" DOUBLE PRECISION,
ADD COLUMN     "partA_condensate_stream_price_cad_m3" DOUBLE PRECISION,
ADD COLUMN     "partA_fx_cad_usd" DOUBLE PRECISION,
ADD COLUMN     "partA_heavy_stream_index_usd_bbl" DOUBLE PRECISION,
ADD COLUMN     "partA_heavy_stream_price_cad_m3" DOUBLE PRECISION,
ADD COLUMN     "partA_premium_heavy_usd_bbl" DOUBLE PRECISION,
ADD COLUMN     "partA_wti_usd_bbl" DOUBLE PRECISION,
ADD COLUMN     "partB_condensate_est_volume_m3" DOUBLE PRECISION,
ADD COLUMN     "partB_final_shrink_pct" DOUBLE PRECISION,
ADD COLUMN     "partB_net_volume_m3" DOUBLE PRECISION,
ADD COLUMN     "partB_shrink_pct_butane" DOUBLE PRECISION,
ADD COLUMN     "partB_shrink_pct_cond" DOUBLE PRECISION,
ADD COLUMN     "partB_shrink_pct_oil" DOUBLE PRECISION,
ADD COLUMN     "partB_shrink_vol_butane_m3" DOUBLE PRECISION,
ADD COLUMN     "partB_shrink_vol_cond_m3" DOUBLE PRECISION,
ADD COLUMN     "partB_shrink_vol_oil_m3" DOUBLE PRECISION,
ADD COLUMN     "partB_total_receipts_m3" DOUBLE PRECISION,
ADD COLUMN     "partB_total_shrinkage_m3" DOUBLE PRECISION,
ADD COLUMN     "partB_total_shrinkage_pct" DOUBLE PRECISION,
ADD COLUMN     "partB_weighted_avg_density_kg_m3" DOUBLE PRECISION;
